"""empty message

Revision ID: 1265733b4099
Revises: 3116d088bed7
Create Date: 2024-12-16 23:38:29.398268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1265733b4099'
down_revision = '3116d088bed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('streaming', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('streaming', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('anime_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite_manga',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('manga_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['manga_id'], ['manga.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    op.drop_table('favorite_manga')
    op.drop_table('favorite_anime')
    op.drop_table('manga')
    op.drop_table('anime')
    # ### end Alembic commands ###
